### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by draja434** [xoceunder/Xtream-UI-Ubuntu20.04#2]
Traceback (most recent call last):
  File "install.py", line 257, in <module>
    printc("X-UI 22f Ubuntu %s Installer - XoceUnder" % rVersion, col.GREEN, 2)
  File "install.py", line 52, in printc
    print("%s \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510 %s" % (rColour, col.ENDC))
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 6-56: ordinal not in range(256)

**Comment by xoceunder** [comment]
what operating system

**Comment by draja434** [comment]
Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-173-generic x86_64)

**Comment by xoceunder** [comment]
Something went wrong since it is status and working without problem

**Comment by draja434** [comment]
tried it few times but same error. Do you have anything for ubuntu 22 ?
